// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTCbGBlsVLOg1fsCSXUfPwymyGwBYjq-k',
    appId: '1:862995028469:web:047cb99b19645fcdf1e8bc',
    messagingSenderId: '862995028469',
    projectId: 'hospital-appointment-51250',
    authDomain: 'hospital-appointment-51250.firebaseapp.com',
    databaseURL: 'https://hospital-appointment-51250-default-rtdb.firebaseio.com',
    storageBucket: 'hospital-appointment-51250.firebasestorage.app',
    measurementId: 'G-V65H3K71LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWS8I7WJEHpUA0HFnueoTo4IRfp-kiRTM',
    appId: '1:862995028469:android:2099d88c33db2554f1e8bc',
    messagingSenderId: '862995028469',
    projectId: 'hospital-appointment-51250',
    databaseURL: 'https://hospital-appointment-51250-default-rtdb.firebaseio.com',
    storageBucket: 'hospital-appointment-51250.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq6GuUn30m9gPvB3dWLUHqMABHl_8Ht_0',
    appId: '1:862995028469:ios:47c526cb4adfdcccf1e8bc',
    messagingSenderId: '862995028469',
    projectId: 'hospital-appointment-51250',
    databaseURL: 'https://hospital-appointment-51250-default-rtdb.firebaseio.com',
    storageBucket: 'hospital-appointment-51250.firebasestorage.app',
    iosBundleId: 'com.example.hosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq6GuUn30m9gPvB3dWLUHqMABHl_8Ht_0',
    appId: '1:862995028469:ios:47c526cb4adfdcccf1e8bc',
    messagingSenderId: '862995028469',
    projectId: 'hospital-appointment-51250',
    databaseURL: 'https://hospital-appointment-51250-default-rtdb.firebaseio.com',
    storageBucket: 'hospital-appointment-51250.firebasestorage.app',
    iosBundleId: 'com.example.hosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTCbGBlsVLOg1fsCSXUfPwymyGwBYjq-k',
    appId: '1:862995028469:web:610952ce2007068ff1e8bc',
    messagingSenderId: '862995028469',
    projectId: 'hospital-appointment-51250',
    authDomain: 'hospital-appointment-51250.firebaseapp.com',
    databaseURL: 'https://hospital-appointment-51250-default-rtdb.firebaseio.com',
    storageBucket: 'hospital-appointment-51250.firebasestorage.app',
    measurementId: 'G-5XHY8X7S1E',
  );

}